[package]
authors = ["Marri Harish <harishmarri551@gmail.com>"]
name = "omniflix-profile"
edition = "2021"
version = "0.1.0"
homepage = ""
repository = ""
license = "Apache-2.0"


[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]

library = []

[dependencies]
cosmwasm-std = { version = "2.2.1", features = [
    "iterator",
    "staking",
    "stargate",
] }
omniflix-std = "1.1.0-beta"
cosmwasm-schema = "2.2.1"
cw-controllers = "2.0.0"
cw2 = "2.0.0"
cw4 = "2.0.0"
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
schemars = "0.8.11"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.31"
semver = "1"
prost = { version = "0.12.3", default-features = false, features = [
    "prost-derive",
] }
anyhow = "1.0.79"

